### ISSUE TITLE
Live blog crashes without current event

### ISSUE THREAD

**Issue by dominikglandorf** [BreakOutEvent/breakout-frontend#264]

**Comment by MkuuWaUjinga** [comment]
Stack trace: 
```
2017-12-10T21:08:25.467Z - info: Trying to get /event/ from backend
2017-12-10T21:08:25.497Z - error:  TypeError: Cannot read property 'year' of undefined
    at /home/azmkuu/Desktop/BreakOut/breakout-frontend/services/api-proxy.js:756:89
    at Generator.next (<anonymous>)
    at onFulfilled (/home/azmkuu/Desktop/BreakOut/breakout-frontend/node_modules/co/index.js:65:19)
    at wrapped (/home/azmkuu/Desktop/BreakOut/breakout-frontend/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
    at Promise.linkTransaction (/home/azmkuu/Desktop/BreakOut/breakout-frontend/node_modules/newrelic/lib/instrumentation/promise.js:295:65)
    at Promise.wrapped (/home/azmkuu/Desktop/BreakOut/breakout-frontend/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
    at __NR_wrappedThenHandler (/home/azmkuu/Desktop/BreakOut/breakout-frontend/node_modules/newrelic/lib/instrumentation/promise.js:471:26)
    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:129:7)
```
