### ISSUE TITLE
 form-data: Arrays are not supported. Error: form-data: Arrays are not supported.

### ISSUE THREAD

**Issue by kenodressel** [BreakOutEvent/breakout-frontend#76]
```
[2016-05-25T09:09:41.178Z] ERROR: breakout-frontend/18 on b77cd2df9b4d:
    form-data: Arrays are not supported. Error: form-data: Arrays are not supported.
        at FormData.append (/src/node_modules/form-data/lib/form_data.js:60:17)
        at appendFormValue (/src/node_modules/request/request.js:339:21)
        at Request.init (/src/node_modules/request/request.js:352:11)
        at new Request (/src/node_modules/request/request.js:142:8)
        at request (/src/node_modules/request/index.js:55:10)
        at Function.post (/src/node_modules/request/index.js:63:12)
        at /src/services/api-proxy.js:180:8
        at Object.API.uploadPicture (/src/services/api-proxy.js:178:10)
        at /src/controller/page-controller/sponsoring.js:87:22
        at next (native)
        at onFulfilled (/src/node_modules/co/index.js:65:19)
        at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by florianschmidt1994** [comment]
@kenodressel Do you remember any details on why / where this issue occured? Didn't appear in the logs recently, I don't know if this is still relevant

**Comment by kenodressel** [comment]
I think this was an issue when uploading multiple images but cant recall details.

**Comment by dominikglandorf** [comment]
In frontend code there is currently no place where API.uploadFile is callable with multiple files selected.
